export type SizePropsType = 'xxs' | 'xs' | 's' | 'm' | 'l' | 'xl' | 'xxl'
export type ViewPropsType =
    'brand'
    | 'secondary'
    | 'base'
    | 'surface'
    | 'flat'
    | 'brand-dark'
    | 'inverse'
    | 'inverse-secondary'
    | 'surface-secondary'
    | 'brand-accent'
export type DisabledPropsType = boolean | ''
export type TagPropsType = 'div' | 'a' | 'button' | 'label' | 'strong' | 'router-link'
export type DirectionPropsType = 'row' | 'column'

export type Maybe<T> = null | undefined | T
export type IconName =
    'chevron-up'
    | 'stop'
    | 'voice-phone'
    | 'voice-scan'
    | 'analytic'
    | 'chevron-down'
    | 'chevron-left'
    | 'chevron-right'
    | 'close'
    | 'diagram'
    | 'mail'
    | 'play'
    | 'check'
    | 'basket'
    | 'bot-ac'
    | 'calendar'
    | 'comment'
    | 'done'
    | 'done-circle'
    | 'refresh'
    | 'sale'
    | 'trash-out'
